In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies=movies.merge(credits,on="title")

In [8]:
movies.shape

(4809, 23)

## include genres,id,keywords,title,overview,cast and crew

In [9]:
movies=movies[["genres","movie_id","keywords","title","overview","cast","crew"]]

In [10]:
movies.shape

(4809, 7)

In [13]:
movies.isnull().sum()

genres      0
movie_id    0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
import ast
def convert(obj):
    x=[]
    for i in ast.literal_eval(obj):
        x.append(i['name'])
    return x

In [21]:
movies['genres']=movies['genres'].apply(convert)

In [22]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies['keywords']=movies['keywords'].apply(convert)

In [24]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def convert2(obj):
    x=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            x.append(i['name'])
            counter+=1
        else:
            break
    return x

In [27]:
movies['cast']=movies['cast'].apply(convert2)

In [28]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
def director(obj):
    x=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            x.append(i['name'])
            break
    return x

In [34]:
movies['crew']=movies['crew'].apply(director)

In [35]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [36]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [37]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

## Remove spaces for better recommendation

In [39]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [40]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [41]:
movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [42]:
new_df=movies[['movie_id','title','tags']]

In [43]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [45]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\chinni\AppData\Local\Temp\ipykernel_1836\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [46]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [47]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\chinni\AppData\Local\Temp\ipykernel_1836\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [48]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

## Vectorization using Bag of Words

### First remove stop words

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
cv=CountVectorizer(max_features=5000,stop_words="english")
vectors=cv.fit_transform(new_df['tags']).toarray()

In [60]:
pip install nltk

Requirement already satisfied: nltk in c:\users\chinni\anaconda3\anaconda\lib\site-packages (3.8.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: click in c:\users\chinni\anaconda3\anaconda\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\chinni\anaconda3\anaconda\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\chinni\anaconda3\anaconda\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\chinni\anaconda3\anaconda\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\chinni\anaconda3\anaconda\lib\site-packages (from click->nltk) (0.4.6)

In [54]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [55]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [61]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\chinni\AppData\Local\Temp\ipykernel_1836\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [62]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [64]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [65]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Using Cosine distance between two vectors for similarity

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

In [71]:
similarity=cosine_similarity(vectors)

In [73]:
list(enumerate(similarity[1]))

[(0, 0.08458258116519013),
 (1, 1.0),
 (2, 0.06063390625908323),
 (3, 0.03883678186903086),
 (4, 0.07504691899113898),
 (5, 0.1145873121285264),
 (6, 0.02111001654603745),
 (7, 0.1292719224987548),
 (8, 0.06262242910851494),
 (9, 0.10226199851298272),
 (10, 0.10846522890932808),
 (11, 0.07504691899113898),
 (12, 0.4070457892053471),
 (13, 0.09513029883089881),
 (14, 0.1355815361366601),
 (15, 0.1107018606925119),
 (16, 0.08346223261119858),
 (17, 0.2533201985524494),
 (18, 0.06021717344277752),
 (19, 0.1107018606925119),
 (20, 0.061357199107789626),
 (21, 0.05797710356524483),
 (22, 0.10727978097782273),
 (23, 0.09095085938862485),
 (24, 0.14097096860865022),
 (25, 0.10846522890932807),
 (26, 0.10846522890932808),
 (27, 0.08783257501821176),
 (28, 0.06063390625908323),
 (29, 0.04583492485141056),
 (30, 0.11778571185788637),
 (31, 0.10090091909944686),
 (32, 0.09007546982220897),
 (33, 0.10289915108550529),
 (34, 0.03300491809922247),
 (35, 0.10502100630210075),
 (36, 0.07756315349925287),
 (37, 0.05564148840746572),
 (38, 0.12862393885688161),
 (39, 0.05797710356524483),
 (40, 0.08134892168199606),
 (41, 0.10006255865485197),
 (42, 0.0),
 (43, 0.07204381596421111),
 (44, 0.03575992699260758),
 (45, 0.06482037235521643),
 (46, 0.11764705882352938),
 (47, 0.12478354962115543),
 (48, 0.11163607017227663),
 (49, 0.03080205518168487),
 (50, 0.08956221510397981),
 (51, 0.04190377370950561),
 (52, 0.07756315349925287),
 (53, 0.11357771260606365),
 (54, 0.03300491809922247),
 (55, 0.07440653318043244),
 (56, 0.07312724241271305),
 (57, 0.15339299776947407),
 (58, 0.09513029883089881),
 (59, 0.09647549158488412),
 (60, 0.0),
 (61, 0.140028008402801),
 (62, 0.13284223283101426),
 (63, 0.06482037235521643),
 (64, 0.03131121455425747),
 (65, 0.020646003475383347),
 (66, 0.11891287353862351),
 (67, 0.05797710356524483),
 (68, 0.0955394632947723),
 (69, 0.07024855763629784),
 (70, 0.053567158400558014),
 (71, 0.10341753799900383),
 (72, 0.11433239009500587),
 (73, 0.03500700210070025),
 (74, 0.07134772412317411),
 (75, 0.16477051091432687),
 (76, 0.050572173742417355),
 (77, 0.04565411576455765),
 (78, 0.053567158400558014),
 (79, 0.10890171046725802),
 (80, 0.03556714970147893),
 (81, 0.09709195467257715),
 (82, 0.026783579200279007),
 (83, 0.07067142711473183),
 (84, 0.08712136837380642),
 (85, 0.12065379433217113),
 (86, 0.05003127932742599),
 (87, 0.029411764705882346),
 (88, 0.0955394632947723),
 (89, 0.04565411576455765),
 (90, 0.09723055853282464),
 (91, 0.14705882352941174),
 (92, 0.06642111641550713),
 (93, 0.05003127932742599),
 (94, 0.16502459049611234),
 (95, 0.049507377148833714),
 (96, 0.08134892168199606),
 (97, 0.09799919151000504),
 (98, 0.13391789600139503),
 (99, 0.056388387443460086),
 (100, 0.03656362120635653),
 (101, 0.08134892168199606),
 (102, 0.06587443126365883),
 (103, 0.08380754741901122),
 (104, 0.14705882352941174),
 (105, 0.10969086361906957),
 (106, 0.13174886252731766),
 (107, 0.06534102628035482),
 (108, 0.05113099925649136),
 (109, 0.17149858514250882),
 (110, 0.023782574707724703),
 (111, 0.07938841860374446),
 (112, 0.05423261445466404),
 (113, 0.04583492485141056),
 (114, 0.04850712500726659),
 (115, 0.09249945801257606),
 (116, 0.050572173742417355),
 (117, 0.0939336436627724),
 (118, 0.01787996349630379),
 (119, 0.04583492485141056),
 (120, 0.0),
 (121, 0.12126781251816646),
 (122, 0.12320822072673948),
 (123, 0.04711428474315455),
 (124, 0.09513029883089881),
 (125, 0.09402964127971364),
 (126, 0.11277677488692017),
 (127, 0.11577058990186095),
 (128, 0.028583097523751468),
 (129, 0.14699878726500756),
 (130, 0.057166195047502935),
 (131, 0.08346223261119858),
 (132, 0.07134772412317411),
 (133, 0.05970814340265321),
 (134, 0.06859943405700353),
 (135, 0.0),
 (136, 0.09901475429766743),
 (137, 0.015923243882462048),
 (138, 0.16269784336399212),
 (139, 0.0844400661841498),
 (140, 0.047565149415449405),
 (141, 0.03080205518168487),
 (142, 0.09095085938862485),
 (143, 0.11458731212852641),
 (144, 0.05292561240249631),
 (145, 0.06105941257599791),
 (146, 0.017149858514250882),
 (147, 0.05882352941176469),
 (148, 0.06859943405700353),
 (149, 0.06149400462680908),
 (150, 0.09647549158488411),
 (151, 0.07151985398521515),
 (152, 0.08823529411764704),
 (153, 0.06239177481057771),
 (154, 0.03241018617760821),
 (155, 0.0),
 (156, 0.041594516540385144),
 (157, 0.0700140042014005),
 (158, 0.11778571185788639),
 (159, 0.06726727939963124),
 (160, 0.07075491376772249),
 (161, 0.03363363969981562),
 (162, 0.0700140042014005),
 (163, 0.026783579200279007),
 (164, 0.08458258116519013),
 (165, 0.024253562503633294),
 (166, 0.05292561240249631),
 (167, 0.1592324388246205),
 (168, 0.10585122480499262),
 (169, 0.11669000700233413),
 (170, 0.06755660236665673),
 (171, 0.12007302660701852),
 (172, 0.07484811885651196),
 (173, 0.04899959575500252),
 (174, 0.08238525545716345),
 (175, 0.05003127932742599),
 (176, 0.06160411036336974),
 (177, 0.0),
 (178, 0.10341753799900383),
 (179, 0.03834824944236852),
 (180, 0.023338001400466827),
 (181, 0.047565149415449405),
 (182, 0.07426106572325057),
 (183, 0.07440653318043244),
 (184, 0.05292561240249631),
 (185, 0.026783579200279007),
 (186, 0.041594516540385144),
 (187, 0.18981415059132414),
 (188, 0.023338001400466827),
 (189, 0.08084520834544433),
 (190, 0.1562904982411873),
 (191, 0.1292719224987548),
 (192, 0.049507377148833714),
 (193, 0.1332593209305539),
 (194, 0.0),
 (195, 0.06262242910851494),
 (196, 0.05492350363810897),
 (197, 0.07817631049941041),
 (198, 0.06063390625908323),
 (199, 0.27749837403772815),
 (200, 0.03834824944236852),
 (201, 0.0),
 (202, 0.03300491809922247),
 (203, 0.05882352941176469),
 (204, 0.02615328904829707),
 (205, 0.07868894753646336),
 (206, 0.09772038812426302),
 (207, 0.08134892168199606),
 (208, 0.09723055853282464),
 (209, 0.10727978097782273),
 (210, 0.05292561240249631),
 (211, 0.025854384499750957),
 (212, 0.04624972900628803),
 (213, 0.041594516540385144),
 (214, 0.0),
 (215, 0.09335200560186731),
 (216, 0.20579830217101058),
 (217, 0.06755660236665673),
 (218, 0.040422604172722164),
 (219, 0.06482037235521643),
 (220, 0.0939336436627724),
 (221, 0.05003127932742599),
 (222, 0.10555008273018725),
 (223, 0.05492350363810897),
 (224, 0.02127178149057585),
 (225, 0.049507377148833714),
 (226, 0.06369297552984819),
 (227, 0.11595420713048966),
 (228, 0.07001400420140048),
 (229, 0.0378777009539285),
 (230, 0.03883678186903086),
 (231, 0.0),
 (232, 0.11764705882352938),
 (233, 0.07312724241271305),
 (234, 0.11357771260606365),
 (235, 0.053567158400558014),
 (236, 0.029411764705882346),
 (237, 0.0700140042014005),
 (238, 0.07817631049941041),
 (239, 0.03859019663395365),
 (240, 0.10006255865485197),
 (241, 0.08346223261119858),
 (242, 0.08574929257125441),
 (243, 0.09799919151000504),
 (244, 0.03241018617760821),
 (245, 0.057166195047502935),
 (246, 0.08028956459037002),
 (247, 0.031846487764924096),
 (248, 0.047565149415449405),
 (249, 0.07312724241271305),
 (250, 0.03363363969981562),
 (251, 0.0),
 (252, 0.06431196942844081),
 (253, 0.044280744277004756),
 (254, 0.04899959575500252),
 (255, 0.026462806201248155),
 (256, 0.03934447376823168),
 (257, 0.056388387443460086),
 (258, 0.05613608914238397),
 (259, 0.06482037235521643),
 (260, 0.09240616554505461),
 (261, 0.02556549962824568),
 (262, 0.09007546982220897),
 (263, 0.10289915108550529),
 (264, 0.0),
 (265, 0.05797710356524483),
 (266, 0.05230657809659414),
 (267, 0.10502100630210075),
 (268, 0.05564148840746572),
 (269, 0.03131121455425747),
 (270, 0.09335200560186731),
 (271, 0.10114434748483471),
 (272, 0.0),
 (273, 0.0893088561378213),
 (274, 0.04067446084099803),
 (275, 0.030316953129541614),
 (276, 0.1320196723968899),
 (277, 0.03742405942825598),
 (278, 0.049507377148833714),
 (279, 0.049507377148833714),
 (280, 0.05492350363810897),
 (281, 0.04583492485141056),
 (282, 0.047565149415449405),
 (283, 0.028988551782622416),
 (284, 0.03883678186903086),
 (285, 0.06193801042615004),
 (286, 0.08199200616907877),
 (287, 0.027461751819054483),
 (288, 0.0),
 (289, 0.04850712500726659),
 (290, 0.06600983619844494),
 (291, 0.05230657809659414),
 (292, 0.0939336436627724),
 (293, 0.03131121455425747),
 (294, 0.09095085938862485),
 (295, 0.05564148840746572),
 (296, 0.06149400462680908),
 (297, 0.023338001400466827),
 (298, 0.0),
 (299, 0.06285566056425843),
 (300, 0.051708768999501914),
 (301, 0.039605901719066965),
 (302, 0.04899959575500252),
 (303, 0.029411764705882346),
 (304, 0.09737260471306503),
 (305, 0.06698164210336598),
 (306, 0.028583097523751468),
 (307, 0.08213292636386628),
 (308, 0.03575992699260758),
 (309, 0.06600983619844494),
 (310, 0.12964074471043285),
 (311, 0.026462806201248155),
 (312, 0.07938841860374446),
 (313, 0.0),
 (314, 0.0),
 (315, 0.11764705882352938),
 (316, 0.020951886854752806),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03500700210070025),
 (320, 0.03241018617760821),
 (321, 0.0),
 (322, 0.08346223261119858),
 (323, 0.03131121455425747),
 (324, 0.02556549962824568),
 (325, 0.1345345587992625),
 (326, 0.029854071701326604),
 (327, 0.057166195047502935),
 (328, 0.057166195047502935),
 (329, 0.11128297681493143),
 (330, 0.10585122480499262),
 (331, 0.09513029883089881),
 (332, 0.08458258116519013),
 (333, 0.025854384499750957),
 (334, 0.10226199851298272),
 (335, 0.04899959575500252),
 (336, 0.07312724241271305),
 (337, 0.024014605321403704),
 (338, 0.0),
 (339, 0.07756315349925287),
 (340, 0.1569197342897824),
 (341, 0.05797710356524483),
 (342, 0.11363310286178552),
 (343, 0.04070627505066527),
 (344, 0.03131121455425747),
 (345, 0.04850712500726659),
 (346, 0.028988551782622416),
 (347, 0.0),
 (348, 0.06482037235521643),
 (349, 0.10585122480499262),
 (350, 0.051708768999501914),
 (351, 0.024014605321403704),
 (352, 0.05797710356524483),
 (353, 0.021780342093451605),
 (354, 0.0),
 (355, 0.05788529495093047),
 (356, 0.06369297552984819),
 (357, 0.0),
 (358, 0.06369297552984819),
 (359, 0.1320196723968899),
 (360, 0.0),
 (361, 0.10585122480499262),
 (362, 0.03363363969981562),
 (363, 0.04190377370950561),
 (364, 0.049507377148833714),
 (365, 0.0),
 (366, 0.029854071701326604),
 (367, 0.0),
 (368, 0.06859943405700353),
 (369, 0.08035073760083702),
 (370, 0.053567158400558014),
 (371, 0.050572173742417355),
 (372, 0.05003127932742599),
 (373, 0.0),
 (374, 0.08028956459037002),
 (375, 0.02160679078507214),
 (376, 0.049507377148833714),
 (377, 0.02449979787750126),
 (378, 0.03241018617760821),
 (379, 0.08939981748151894),
 (380, 0.027461751819054483),
 (381, 0.08856148855400951),
 (382, 0.0),
 (383, 0.06937459350943204),
 (384, 0.12126781251816646),
 (385, 0.030316953129541614),
 (386, 0.06937459350943204),
 (387, 0.025015639663712994),
 (388, 0.024253562503633294),
 (389, 0.12320822072673948),
 (390, 0.02782074420373286),
 (391, 0.07974522228289),
 (392, 0.09553946329477228),
 (393, 0.0),
 (394, 0.02615328904829707),
 (395, 0.0),
 (396, 0.023124864503144014),
 (397, 0.05492350363810897),
 (398, 0.046676002800933654),
 (399, 0.025015639663712994),
 (400, 0.06369297552984819),
 (401, 0.0),
 (402, 0.05492350363810897),
 (403, 0.1097907187727647),
 (404, 0.0),
 (405, 0.05882352941176469),
 (406, 0.0),
 (407, 0.06755660236665673),
 (408, 0.034299717028501764),
 (409, 0.049507377148833714),
 (410, 0.051708768999501914),
 (411, 0.08346223261119858),
 (412, 0.15171652122725207),
 (413, 0.05797710356524483),
 (414, 0.03131121455425747),
 (415, 0.01871202971412799),
 (416, 0.053567158400558014),
 (417, 0.034299717028501764),
 (418, 0.03742405942825598),
 (419, 0.07276068751089988),
 (420, 0.09513029883089881),
 (421, 0.0),
 (422, 0.03080205518168487),
 (423, 0.04356068418690321),
 (424, 0.03908815524970521),
 (425, 0.09007546982220897),
 (426, 0.056816551430892745),
 (427, 0.08458258116519013),
 (428, 0.059016710652347516),
 (429, 0.0),
 (430, 0.0),
 (431, 0.05113099925649136),
 (432, 0.04850712500726659),
 (433, 0.03300491809922247),
 (434, 0.025015639663712994),
 (435, 0.07484811885651196),
 (436, 0.02711630722733202),
 (437, 0.05492350363810897),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.024014605321403704),
 (443, 0.06755660236665673),
 (444, 0.024753688574416857),
 (445, 0.02615328904829707),
 (446, 0.02449979787750126),
 (447, 0.04543108504242546),
 (448, 0.045037734911104486),
 (449, 0.028988551782622416),
 (450, 0.022518867455552243),
 (451, 0.026462806201248155),
 (452, 0.03241018617760821),
 (453, 0.025854384499750957),
 (454, 0.04899959575500252),
 (455, 0.042874646285627205),
 (456, 0.02291746242570528),
 (457, 0.12126781251816646),
 (458, 0.04583492485141056),
 (459, 0.03656362120635653),
 (460, 0.05113099925649136),
 (461, 0.08956221510397981),
 (462, 0.034129494057038114),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.07669649888473704),
 (467, 0.06698164210336598),
 (468, 0.05882352941176469),
 (469, 0.08380754741901122),
 (470, 0.04802921064280741),
 (471, 0.09007546982220897),
 (472, 0.11433239009500587),
 (473, 0.04899959575500252),
 (474, 0.0),
 (475, 0.06937459350943204),
 (476, 0.03575992699260758),
 (477, 0.0),
 (478, 0.057166195047502935),
 (479, 0.03720326659021622),
 (480, 0.07756315349925287),
 (481, 0.025015639663712994),
 (482, 0.0),
 (483, 0.09901475429766741),
 (484, 0.06160411036336974),
 (485, 0.08346223261119858),
 (486, 0.10138954626279946),
 (487, 0.06726727939963124),
 (488, 0.05278615073083401),
 (489, 0.042874646285627205),
 (490, 0.07484811885651196),
 (491, 0.06333004963811235),
 (492, 0.08035073760083702),
 (493, 0.03241018617760821),
 (494, 0.03500700210070025),
 (495, 0.06726727939963124),
 (496, 0.017977936632415484),
 (497, 0.034299717028501764),
 (498, 0.07151985398521515),
 (499, 0.02782074420373286),
 (500, 0.027461751819054483),
 (501, 0.06482037235521643),
 (502, 0.04711428474315455),
 (503, 0.07938841860374446),
 (504, 0.03241018617760821),
 (505, 0.07151985398521515),
 (506, 0.0),
 (507, 0.06755660236665673),
 (508, 0.13391789600139503),
 (509, 0.07001400420140048),
 (510, 0.02615328904829707),
 (511, 0.09723055853282464),
 (512, 0.028988551782622416),
 (513, 0.051708768999501914),
 (514, 0.07756315349925287),
 (515, 0.05230657809659414),
 (516, 0.0),
 (517, 0.06333004963811235),
 (518, 0.046676002800933654),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.05113099925649136),
 (524, 0.030316953129541614),
 (525, 0.025015639663712994),
 (526, 0.0),
 (527, 0.0),
 (528, 0.023557142371577276),
 (529, 0.025286086871208677),
 (530, 0.08823529411764704),
 (531, 0.04899959575500252),
 (532, 0.0),
 (533, 0.031846487764924096),
 (534, 0.044280744277004756),
 (535, 0.051708768999501914),
 (536, 0.023782574707724703),
 (537, 0.07151985398521515),
 (538, 0.0),
 (539, 0.05882352941176469),
 (540, 0.05292561240249631),
 (541, 0.04465442806891065),
 (542, 0.05863223287455781),
 (543, 0.12507819831856498),
 (544, 0.08823529411764704),
 (545, 0.02615328904829707),
 (546, 0.06726727939963124),
 (547, 0.08696565534786725),
 (548, 0.0),
 (549, 0.07585826061362604),
 (550, 0.0),
 (551, 0.07974522228289),
 (552, 0.0),
 (553, 0.030316953129541614),
 (554, 0.029854071701326604),
 (555, 0.0158550498051498),
 (556, 0.028194193721730043),
 (557, 0.025854384499750957),
 (558, 0.0),
 (559, 0.031846487764924096),
 (560, 0.057166195047502935),
 (561, 0.03363363969981562),
 (562, 0.03241018617760821),
 (563, 0.05423261445466404),
 (564, 0.03131121455425747),
 (565, 0.06937459350943204),
 (566, 0.07585826061362604),
 (567, 0.0),
 (568, 0.05970814340265321),
 (569, 0.10006255865485197),
 (570, 0.03575992699260758),
 (571, 0.022327214034455325),
 (572, 0.09086217008485092),
 (573, 0.02195814375455294),
 (574, 0.024753688574416857),
 (575, 0.04802921064280741),
 (576, 0.05492350363810897),
 (577, 0.05970814340265321),
 (578, 0.039605901719066965),
 (579, 0.029411764705882346),
 (580, 0.02556549962824568),
 (581, 0.12320822072673948),
 (582, 0.04711428474315455),
 (583, 0.11961783342433499),
 (584, 0.08574929257125441),
 (585, 0.025854384499750957),
 (586, 0.047565149415449405),
 (587, 0.12507819831856498),
 (588, 0.02711630722733202),
 (589, 0.040996003084539386),
 (590, 0.031846487764924096),
 (591, 0.044280744277004756),
 (592, 0.06698164210336598),
 (593, 0.020072391147592506),
 (594, 0.05230657809659414),
 (595, 0.04850712500726659),
 (596, 0.09799919151000504),
 (597, 0.0939336436627724),
 (598, 0.0),
 (599, 0.014494275891311208),
 (600, 0.04802921064280741),
 (601, 0.05306618532579187),
 (602, 0.07204381596421111),
 (603, 0.057166195047502935),
 (604, 0.0700140042014005),
 (605, 0.0),
 (606, 0.0),
 (607, 0.10176568762666317),
 (608, 0.0),
 (609, 0.049507377148833714),
 (610, 0.07669649888473704),
 (611, 0.024253562503633294),
 (612, 0.0893088561378213),
 (613, 0.03834824944236852),
 (614, 0.051708768999501914),
 (615, 0.03241018617760821),
 (616, 0.03656362120635653),
 (617, 0.026462806201248155),
 (618, 0.09335200560186731),
 (619, 0.05423261445466404),
 (620, 0.0),
 (621, 0.034299717028501764),
 (622, 0.022327214034455325),
 (623, 0.047565149415449405),
 (624, 0.07151985398521515),
 (625, 0.0),
 (626, 0.028988551782622416),
 (627, 0.11504474832710555),
 (628, 0.05113099925649136),
 (629, 0.05113099925649136),
 (630, 0.025854384499750957),
 (631, 0.026783579200279007),
 (632, 0.0),
 (633, 0.04711428474315455),
 (634, 0.05230657809659414),
 (635, 0.023124864503144014),
 (636, 0.07426106572325057),
 (637, 0.0),
 (638, 0.0),
 (639, 0.02556549962824568),
 (640, 0.06333004963811235),
 (641, 0.0),
 (642, 0.03080205518168487),
 (643, 0.07938841860374446),
 (644, 0.05292561240249631),
 (645, 0.07001400420140048),
 (646, 0.08346223261119858),
 (647, 0.0),
 (648, 0.0),
 (649, 0.10846522890932808),
 (650, 0.05492350363810897),
 (651, 0.08035073760083702),
 (652, 0.0),
 (653, 0.03742405942825598),
 (654, 0.08783257501821176),
 (655, 0.025286086871208677),
 (656, 0.025854384499750957),
 (657, 0.07312724241271305),
 (658, 0.07669649888473704),
 (659, 0.10713431680111603),
 (660, 0.09901475429766741),
 (661, 0.08783257501821176),
 (662, 0.0),
 (663, 0.0),
 (664, 0.12738595105969638),
 (665, 0.07204381596421111),
 (666, 0.05292561240249631),
 (667, 0.0),
 (668, 0.07151985398521515),
 (669, 0.0),
 (670, 0.0),
 (671, 0.024014605321403704),
 (672, 0.029854071701326604),
 (673, 0.0),
 (674, 0.05003127932742599),
 (675, 0.047565149415449405),
 (676, 0.06063390625908323),
 (677, 0.026462806201248155),
 (678, 0.06063390625908323),
 (679, 0.0),
 (680, 0.026462806201248155),
 (681, 0.0),
 (682, 0.0),
 (683, 0.05113099925649136),
 (684, 0.0),
 (685, 0.03500700210070025),
 (686, 0.06726727939963124),
 (687, 0.05492350363810897),
 (688, 0.02291746242570528),
 (689, 0.053567158400558014),
 (690, 0.05292561240249631),
 (691, 0.0939336436627724),
 (692, 0.023124864503144014),
 (693, 0.0),
 (694, 0.11562432251572008),
 (695, 0.10502100630210075),
 (696, 0.045037734911104486),
 (697, 0.07817631049941041),
 (698, 0.04583492485141056),
 (699, 0.0),
 (700, 0.06063390625908323),
 (701, 0.0),
 (702, 0.047565149415449405),
 (703, 0.022518867455552243),
 (704, 0.024014605321403704),
 (705, 0.051708768999501914),
 (706, 0.04583492485141056),
 (707, 0.0700140042014005),
 (708, 0.02615328904829707),
 (709, 0.04356068418690321),
 (710, 0.04070627505066527),
 (711, 0.08238525545716345),
 (712, 0.02556549962824568),
 (713, 0.0),
 (714, 0.0),
 (715, 0.10502100630210075),
 (716, 0.08574929257125441),
 (717, 0.09249945801257606),
 (718, 0.023782574707724703),
 (719, 0.041594516540385144),
 (720, 0.0),
 (721, 0.034299717028501764),
 (722, 0.07585826061362604),
 (723, 0.0),
 (724, 0.07504691899113898),
 (725, 0.0),
 (726, 0.0),
 (727, 0.032555850669650596),
 (728, 0.07669649888473704),
 (729, 0.0),
 (730, 0.07996162762590017),
 (731, 0.08238525545716345),
 (732, 0.047565149415449405),
 (733, 0.06482037235521643),
 (734, 0.07067142711473183),
 (735, 0.023557142371577276),
 (736, 0.09095085938862485),
 (737, 0.05423261445466404),
 (738, 0.07312724241271305),
 (739, 0.040422604172722164),
 (740, 0.04583492485141056),
 (741, 0.05882352941176469),

In [77]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    movies_list=sorted(list(enumerate(similarity[movie_index])),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [ ]:
import pickle

In [ ]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))